<div class="content-header">
<table cellspacing="0">
    <tr>
        <td style="width:50%;"><h3 class="icon-head head-products"><?php echo Mage::helper('attributemanager')->__('Manage attributes') ?></h3></td>
        <td class="a-right">
        </td>
    </tr>
</table>
</div>
<div>
    <div align="center">
    	<h3 class="icon-head"><u><?php echo Mage::helper('attributemanager')->__('Choose Attributes to Manage') ?></u></h3>
    	<br/><br/>
    	<h3 class="icon-head">
    	<a href="<?php echo $this->getUrl('*');?>index/catalog_category/filter//"><?php echo Mage::helper('attributemanager')->__('Category\'s Attributes') ?></a>
    	<br/>
    	<a href="<?php echo $this->getUrl('*');?>index/customer/filter//"><?php echo Mage::helper('attributemanager')->__('Customer\'s Attributes') ?></a>
    	<br/>
    	<a href="<?php echo $this->getUrl('*');?>index/address/filter//"><?php echo Mage::helper('attributemanager')->__('Customer Address\'s Attributes') ?></a>
    	<br/>
    	<a href="<?php echo $this->getUrl('*');?>index/order/filter//"><?php echo Mage::helper('attributemanager')->__('Order\'s Attributes') ?></a>
    	<br/>
    	<a href="<?php echo $this->getUrl('*');?>index/order_address/filter//"><?php echo Mage::helper('attributemanager')->__('Order Address\'s Attributes') ?></a>
    	<br/>
    	<a href="<?php echo $this->getUrl('*');?>index/order_item/filter//"><?php echo Mage::helper('attributemanager')->__('Order Item\'s Attributes') ?></a>
    	<br/>
    	<a href="<?php echo $this->getUrl('*');?>index/order_payment/filter//"><?php echo Mage::helper('attributemanager')->__('Order Payment\'s Attributes') ?></a>
    	<br/>
    	<a href="<?php echo $this->getUrl('*');?>index/order_status_history/filter//"><?php echo Mage::helper('attributemanager')->__('Order Status History\'s Attributes') ?></a>
    	<br/>
    	<a href="<?php echo $this->getUrl('*');?>index/invoice_item/filter//"><?php echo Mage::helper('attributemanager')->__('Invoice\'s Attributes') ?></a>
    	<br/>
    	<a href="<?php echo $this->getUrl('*');?>index/invoice_item/filter//"><?php echo Mage::helper('attributemanager')->__('Invoice Item\'s Attributes') ?></a>
    	<br/>
    	<a href="<?php echo $this->getUrl('*');?>index/invoice_comment/filter//"><?php echo Mage::helper('attributemanager')->__('Invoice Comment\'s Attributes') ?></a>
    	</h3>
    </div>
</div>